### ISSUE TITLE
No fcitx?

### ISSUE THREAD

**Issue by kwaiching** [YQ-YSY/one-hand_Rime#1]
No fcitx?

**Comment by YQ-YSY** [comment]
问过 fcitx 的开发者，他们说不支持数字小键盘的输入，数字只能用来选字，以没办法。
Ibus-table 可以用数字输入，但用数字小键盘时会自动多加一个回车，我不是程序员，也没办法。

**Comment by kwaiching** [comment]
https://github.com/kwaiching/rime_tyhgb_stroke

fcitx + ibus
